# Generated by Django 5.2.7 on 2025-11-05 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='examform',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examform',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='examform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='examform',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='examform',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='examform',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examform',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examform',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('winter', 'Winter'), ('summer', 'Summer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examform',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
